spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: cache-updater-group
      auto-offset-reset: earliest
    listener:
      type: batch
    producer:
      acks: all
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
debezium:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group: cache-updater-group
    topic: dbserver.testdb.products
